language: python
python:
  - "3.6"

services:
  - postgresql

env:
  global:
  - DATABASE_URI: 'postgres://postgres:@localhost:5432/test'

# install dependencies
install: 'pip install -r requirements.txt'

# create a test database
before_script:
  - psql -c 'create database test;' -U postgres

# command to run tests
script: nosetests

# after_success:
#   - codecov
